### PR TITLE
Remove glibc dependency

### LINKED ISSUE #48: Support for `musl` (alternative libc implementation)
Hello, I'm trying to use `isolate` in an alpine-linux docker image. Alpine linux uses `musl` for the libc implementation, and there's a difference in `ftw.h` implementation between [`musl`](http://git.musl-libc.org/cgit/musl/tree/src/misc/nftw.c) and [`glibc`](https://github.com/lattera/glibc/blob/master/io/ftw.h): `FTW_CONTINUE` enum flag only exists in `glibc/ftw.h`.

`FTW_CONTINUE` is used in `util.c` so I cannot directly compile this unless you define `FTW_CONTINUE` explicitly, but I'm a newbie in linux and I don't know the proper way to fix the problem, so I'm creating the issue.

### PR DESCRIPTION
**Pull request by chongkong**
Resolves #48, suggested by @seirl

### CODE REVIEW

**Comment by seirl** [comment]
To add to what the title is saying, this removes the glibc dependency *and* fixes an incorrect usage of the `nftw` function, as explained here: https://github.com/ioi/isolate/issues/48#issuecomment-372295529

**Comment by gollux** [comment]
Fixed in master.

**Comment by chongkong** [comment]
It seems the latest commit ea175fa does not remove all `FTW_CONTINUE` usage. There's one more `FTW_CONTINUE` remaining in util.c

**Comment by gollux** [comment]
> It seems the latest commit ea175fa does not remove all `FTW_CONTINUE` usage.
> There's one more `FTW_CONTINUE` remaining in util.c

Sorry, it should be gone now.

**Pull request closed without merging**
